/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess.execution;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        final ChessGame game = new ChessGame();

        while (true) {
            LOGGER.info(game.getBoardPrinter().printBoard());
            game.nextPlayersTurn();
        }
    }


}
