/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

import chess.execution.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
}
